spring.application.name=Gerenciamento de Tarefas
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/aula_web
spring.datasource.username=postgres
spring.datasource.password=senai
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true